import * as flatbuffers from 'flatbuffers';
import { getLevmarFns } from './ffi';
// Paths below are generated by flatc at build time (CMake flatbuffers_gen target).
import { LevMarRequest } from './generated/stoch-fit-proto/lev-mar-request';
import { BoxReflSettings as FBBoxReflSettings } from './generated/stoch-fit-proto/box-refl-settings';
import { ReflFitResult } from './generated/stoch-fit-proto/refl-fit-result';
import { ReflGenerateResult } from './generated/stoch-fit-proto/refl-generate-result';
import { RhoFitResult } from './generated/stoch-fit-proto/rho-fit-result';
import { RhoGenerateResult as FBRhoGenerateResult } from './generated/stoch-fit-proto/rho-generate-result';
import { BoxStochFitResult } from './generated/stoch-fit-proto/box-stoch-fit-result';

// ── Public interfaces ─────────────────────────────────────────────────────────

export interface BoxReflSettingsInput {
  directory: string;
  q: number[];
  refl: number[];
  reflError: number[];
  qError: number[];
  ul: number[];
  ll: number[];
  paramPercs: number[];
  qPoints: number;
  oneSigma: boolean;
  writeFiles: boolean;
  subSLD: number;
  supSLD: number;
  boxes: number;
  wavelength: number;
  qSpread: number;
  forcenorm: boolean;
  impNorm: boolean;
  fitFunc: number;
  lowQOffset: number;
  highQOffset: number;
  iterations: number;
  miedp?: number[];
  zIncrement?: number[];
  zLength?: number;
}

export interface LMFitResult {
  parameters: number[];
  covariance: number[];
  info: number[];
}

export interface RhoEDPResult {
  ed: number[];
  boxED: number[];
}

export interface StochFitResult extends LMFitResult {
  paramArray: number[];
  chiSquareArray: number[];
  paramArraySize: number;
}

// ── Buffer sizing ─────────────────────────────────────────────────────────────

const MAX_FIT_BUF       =  64 * 1024;   //  64 KB  (params + covar + info)
const MAX_GENERATE_BUF  =  64 * 1024;   //  64 KB  (reflectivity or EDP arrays)
// StochFitBoxModel can return up to 1000 solutions × paramSize × 3 arrays
const MAX_STOCHFIT_BUF  =   2 * 1024 * 1024;  // 2 MB

// ── FlatBuffers helpers ───────────────────────────────────────────────────────

function readResult<T>(out: Uint8Array, written: number, getRootAs: (bb: flatbuffers.ByteBuffer) => T): T {
  if (written <= 0) throw new Error(`LevMar FFI call returned ${written}`);
  return getRootAs(new flatbuffers.ByteBuffer(out.subarray(0, written)));
}

function buildRequest(input: BoxReflSettingsInput, params: number[]): Uint8Array {
  const builder = new flatbuffers.Builder(8192);
  const n = input.qPoints;
  const p = input.ul.length;
  const zLen = input.zLength ?? 0;

  const dirOff     = builder.createString(input.directory);
  const qOff       = FBBoxReflSettings.createQVector(builder, input.q.slice(0, n));
  const reflOff    = FBBoxReflSettings.createReflVector(builder, input.refl.slice(0, n));
  const reflErrOff = FBBoxReflSettings.createReflErrorVector(builder, input.reflError.slice(0, n));
  const qErrOff    = FBBoxReflSettings.createQErrorVector(builder, input.qError.slice(0, n));
  const ulOff      = FBBoxReflSettings.createUlVector(builder, input.ul.slice(0, p));
  const llOff      = FBBoxReflSettings.createLlVector(builder, input.ll.slice(0, p));
  const percOff    = FBBoxReflSettings.createParamPercsVector(builder, input.paramPercs);
  const miedpOff   = FBBoxReflSettings.createMiedpVector(builder, (zLen > 0 && input.miedp) ? input.miedp.slice(0, zLen) : []);
  const zIncOff    = FBBoxReflSettings.createZIncrementVector(builder, (zLen > 0 && input.zIncrement) ? input.zIncrement.slice(0, zLen) : []);

  FBBoxReflSettings.startBoxReflSettings(builder);
  FBBoxReflSettings.addDirectory(builder, dirOff);
  FBBoxReflSettings.addQ(builder, qOff);
  FBBoxReflSettings.addRefl(builder, reflOff);
  FBBoxReflSettings.addReflError(builder, reflErrOff);
  FBBoxReflSettings.addQError(builder, qErrOff);
  FBBoxReflSettings.addUl(builder, ulOff);
  FBBoxReflSettings.addLl(builder, llOff);
  FBBoxReflSettings.addParamPercs(builder, percOff);
  FBBoxReflSettings.addQPoints(builder, input.qPoints);
  FBBoxReflSettings.addOneSigma(builder, input.oneSigma ? 1 : 0);
  FBBoxReflSettings.addWriteFiles(builder, input.writeFiles ? 1 : 0);
  FBBoxReflSettings.addSubSld(builder, input.subSLD);
  FBBoxReflSettings.addSupSld(builder, input.supSLD);
  FBBoxReflSettings.addBoxes(builder, input.boxes);
  FBBoxReflSettings.addWavelength(builder, input.wavelength);
  FBBoxReflSettings.addQSpread(builder, input.qSpread);
  FBBoxReflSettings.addForcenorm(builder, input.forcenorm ? 1 : 0);
  FBBoxReflSettings.addImpNorm(builder, input.impNorm ? 1 : 0);
  FBBoxReflSettings.addFitFunc(builder, input.fitFunc);
  FBBoxReflSettings.addLowQOffset(builder, input.lowQOffset);
  FBBoxReflSettings.addHighQOffset(builder, input.highQOffset);
  FBBoxReflSettings.addIterations(builder, input.iterations);
  FBBoxReflSettings.addMiedp(builder, miedpOff);
  FBBoxReflSettings.addZIncrement(builder, zIncOff);
  FBBoxReflSettings.addZLength(builder, zLen);
  const settingsOff = FBBoxReflSettings.endBoxReflSettings(builder);

  const paramsOff = LevMarRequest.createParametersVector(builder, params);

  LevMarRequest.startLevMarRequest(builder);
  LevMarRequest.addSettings(builder, settingsOff);
  LevMarRequest.addParameters(builder, paramsOff);
  const root = LevMarRequest.endLevMarRequest(builder);
  builder.finish(root);

  return builder.asUint8Array();
}

// ── Exported functions ────────────────────────────────────────────────────────

export function levmarFastReflFit(input: BoxReflSettingsInput, params: number[]): LMFitResult {
  const fns = getLevmarFns();
  const inBuf = buildRequest(input, params);
  const outBuf = new Uint8Array(MAX_FIT_BUF);
  const written: number = fns['FastReflfit'](inBuf, inBuf.length, outBuf, outBuf.length);
  const r = readResult(outBuf, written, (bb) => ReflFitResult.getRootAsReflFitResult(bb));
  return {
    parameters: Array.from(r.parametersArray() ?? []),
    covariance: Array.from(r.covarArray() ?? []),
    info:       Array.from(r.infoArray() ?? []),
  };
}

export function levmarFastReflGenerate(input: BoxReflSettingsInput, params: number[]): number[] {
  const fns = getLevmarFns();
  const inBuf = buildRequest(input, params);
  const outBuf = new Uint8Array(MAX_GENERATE_BUF);
  const written: number = fns['FastReflGenerate'](inBuf, inBuf.length, outBuf, outBuf.length);
  const r = readResult(outBuf, written, (bb) => ReflGenerateResult.getRootAsReflGenerateResult(bb));
  return Array.from(r.reflectivityArray() ?? []);
}

export function levmarRhoFit(input: BoxReflSettingsInput, params: number[]): LMFitResult {
  const fns = getLevmarFns();
  const inBuf = buildRequest(input, params);
  const outBuf = new Uint8Array(MAX_FIT_BUF);
  const written: number = fns['Rhofit'](inBuf, inBuf.length, outBuf, outBuf.length);
  const r = readResult(outBuf, written, (bb) => RhoFitResult.getRootAsRhoFitResult(bb));
  return {
    parameters: Array.from(r.parametersArray() ?? []),
    covariance: Array.from(r.covarArray() ?? []),
    info:       Array.from(r.infoArray() ?? []),
  };
}

export function levmarRhoGenerate(input: BoxReflSettingsInput, params: number[]): RhoEDPResult {
  const fns = getLevmarFns();
  const inBuf = buildRequest(input, params);
  const outBuf = new Uint8Array(MAX_GENERATE_BUF);
  const written: number = fns['RhoGenerate'](inBuf, inBuf.length, outBuf, outBuf.length);
  const r = readResult(outBuf, written, (bb) => FBRhoGenerateResult.getRootAsRhoGenerateResult(bb));
  return {
    ed:    Array.from(r.edArray() ?? []),
    boxED: Array.from(r.boxEdArray() ?? []),
  };
}

export function levmarStochFit(input: BoxReflSettingsInput, params: number[]): StochFitResult {
  const fns = getLevmarFns();
  const inBuf = buildRequest(input, params);
  const outBuf = new Uint8Array(MAX_STOCHFIT_BUF);
  const written: number = fns['StochFitBoxModel'](inBuf, inBuf.length, outBuf, outBuf.length);
  const r = readResult(outBuf, written, (bb) => BoxStochFitResult.getRootAsBoxStochFitResult(bb));
  const n = r.paramArraySize();
  const p = params.length;
  return {
    parameters:     Array.from(r.parametersArray() ?? []),
    covariance:     Array.from(r.covarArrayArray() ?? []),
    info:           Array.from((r.infoArray() ?? []).slice(0, 10)),  // first solution info
    paramArray:     Array.from((r.paramArrayArray() ?? []).slice(0, n * p)),
    chiSquareArray: Array.from((r.chisquareArrayArray() ?? []).slice(0, n)),
    paramArraySize: n,
  };
}
