import * as flatbuffers from 'flatbuffers';
import fs from 'fs';
import { getStochFns } from './ffi';
// Paths below are generated by flatc at build time (CMake flatbuffers_gen target).
// If import paths are wrong after first build, check gui/src/main/native/generated/stoch-fit-proto/.
import { InitRequest } from './generated/stoch-fit-proto/init-request';
import { ReflSettings as FBReflSettings } from './generated/stoch-fit-proto/refl-settings';
import { StochRunState as FBStochRunState } from './generated/stoch-fit-proto/stoch-run-state';
import { GetDataResult } from './generated/stoch-fit-proto/get-data-result';
import { GetRunStateResult } from './generated/stoch-fit-proto/get-run-state-result';
import { ArraySizesResult } from './generated/stoch-fit-proto/array-sizes-result';
import { SaParamsResult } from './generated/stoch-fit-proto/sa-params-result';

// ── Public interfaces ─────────────────────────────────────────────────────────

export interface ReflSettingsInput {
  directory: string;
  q: number[];
  refl: number[];
  reflError: number[];
  qError: number[];
  qPoints: number;
  subSLD: number;
  filmSLD: number;
  supSLD: number;
  boxes: number;
  filmAbs: number;
  subAbs: number;
  supAbs: number;
  wavelength: number;
  useSurfAbs: boolean;
  qSpread: number;
  forcenorm: boolean;
  forcesig: number;
  debug: boolean;
  neutron: boolean;
  resolution: number;
  filmLength: number;
  impnorm: boolean;
  objectivefunction: number;
  paramtemp: number;
  sigmasearch: number;
  normSearchPerc: number;
  absSearchPerc: number;
  algorithm: number;
  inittemp: number;
  platiter: number;
  slope: number;
  gamma: number;
  stunFunc: number;
  adaptive: boolean;
  tempiter: number;
  stunDeciter: number;
  gammadec: number;
  critEdgeOffset: number;
  highQOffset: number;
  iterations: number;
  title: string;
  useGpu: boolean;
  gpuChains: number;
}

export interface FitData {
  zRange: number[];
  rho: number[];
  qRange: number[];
  refl: number[];
  roughness: number;
  chiSquare: number;
  goodnessOfFit: number;
  isFinished: boolean;
  iterationsCompleted: number;
}

export interface SAParams {
  lowestEnergy: number;
  temp: number;
  mode: number;
}

export interface StochRunStateOutput {
  roughness: number;
  filmAbsInput: number;
  surfAbs: number;
  temperature: number;
  impNorm: number;
  avgfSTUN: number;
  bestSolution: number;
  chiSquare: number;
  goodnessOfFit: number;
  iteration: number;
  edValues: number[];
  edCount: number;
}

export interface StochSessionFile {
  version: number;
  savedAt: string;
  dataFile: string;
  settings: Record<string, unknown>;
  saState: StochRunStateOutput;
}

// ── Buffer sizing ─────────────────────────────────────────────────────────────

// Conservative upper bound for GetData output (Rho + Refl arrays + FlatBuffer overhead).
// Sized for up to ~8000 data points × 4 arrays × 8 bytes + overhead.
const MAX_DATA_BUF  = 256 * 1024;  // 256 KB
const MAX_STATE_BUF =   4 * 1024;  //   4 KB (scalars + edValues)
const MAX_SMALL_BUF =   1 * 1024;  //   1 KB (ArraySizes, SAParams)

// ── FlatBuffers helpers ───────────────────────────────────────────────────────

function readResult<T>(
  outBuf: Uint8Array,
  written: number,
  getRootAs: (bb: flatbuffers.ByteBuffer) => T,
): T {
  if (written <= 0) throw new Error(`FlatBuffers call returned ${written}`);
  const bb = new flatbuffers.ByteBuffer(outBuf.subarray(0, written));
  return getRootAs(bb);
}

// ── SA lifecycle ──────────────────────────────────────────────────────────────

export function stochInit(settings: ReflSettingsInput, runState: StochRunStateOutput | null = null): void {
  const fns = getStochFns();
  const builder = new flatbuffers.Builder(8192);

  // Inline vectors must be created before the table
  const n = settings.qPoints;
  const dirOff   = builder.createString(settings.directory);
  const titleOff = builder.createString(settings.title);
  const qOff     = FBReflSettings.createQVector(builder, settings.q.slice(0, n));
  const reflOff  = FBReflSettings.createReflVector(builder, settings.refl.slice(0, n));
  const reflErrOff = FBReflSettings.createReflErrorVector(builder, settings.reflError.slice(0, n));
  const qErrOff  = FBReflSettings.createQErrorVector(builder, settings.qError.slice(0, n));

  FBReflSettings.startReflSettings(builder);
  FBReflSettings.addDirectory(builder, dirOff);
  FBReflSettings.addQ(builder, qOff);
  FBReflSettings.addRefl(builder, reflOff);
  FBReflSettings.addReflError(builder, reflErrOff);
  FBReflSettings.addQError(builder, qErrOff);
  FBReflSettings.addQPoints(builder, settings.qPoints);
  FBReflSettings.addSubSld(builder, settings.subSLD);
  FBReflSettings.addFilmSld(builder, settings.filmSLD);
  FBReflSettings.addSupSld(builder, settings.supSLD);
  FBReflSettings.addBoxes(builder, settings.boxes);
  FBReflSettings.addFilmAbs(builder, settings.filmAbs);
  FBReflSettings.addSubAbs(builder, settings.subAbs);
  FBReflSettings.addSupAbs(builder, settings.supAbs);
  FBReflSettings.addWavelength(builder, settings.wavelength);
  FBReflSettings.addUseSurfAbs(builder, settings.useSurfAbs ? 1 : 0);
  FBReflSettings.addQErr(builder, settings.qSpread);
  FBReflSettings.addForcenorm(builder, settings.forcenorm ? 1 : 0);
  FBReflSettings.addForcesig(builder, settings.forcesig);
  FBReflSettings.addDebug(builder, settings.debug ? 1 : 0);
  FBReflSettings.addXrOnly(builder, settings.neutron ? 0 : 1);
  FBReflSettings.addResolution(builder, settings.resolution);
  FBReflSettings.addFilmLength(builder, settings.filmLength);
  FBReflSettings.addImpnorm(builder, settings.impnorm ? 1 : 0);
  FBReflSettings.addObjectivefunction(builder, settings.objectivefunction);
  FBReflSettings.addParamtemp(builder, settings.paramtemp);
  FBReflSettings.addSigmasearch(builder, settings.sigmasearch);
  FBReflSettings.addNormalizationSearchPerc(builder, settings.normSearchPerc);
  FBReflSettings.addAbsorptionSearchPerc(builder, settings.absSearchPerc);
  FBReflSettings.addAlgorithm(builder, settings.algorithm);
  FBReflSettings.addInittemp(builder, settings.inittemp);
  FBReflSettings.addPlatiter(builder, settings.platiter);
  FBReflSettings.addSlope(builder, settings.slope);
  FBReflSettings.addGamma(builder, settings.gamma);
  FBReflSettings.addStunFunc(builder, settings.stunFunc);
  FBReflSettings.addAdaptive(builder, settings.adaptive ? 1 : 0);
  FBReflSettings.addTempiter(builder, settings.tempiter);
  FBReflSettings.addStunDecIter(builder, settings.stunDeciter);
  FBReflSettings.addGammadec(builder, settings.gammadec);
  FBReflSettings.addCritEdgeOffset(builder, settings.critEdgeOffset);
  FBReflSettings.addHighQOffset(builder, settings.highQOffset);
  FBReflSettings.addIterations(builder, settings.iterations);
  FBReflSettings.addIterationsCompleted(builder, 0);
  FBReflSettings.addChiSquare(builder, 0.0);
  FBReflSettings.addUseGpu(builder, settings.useGpu ? 1 : 0);
  FBReflSettings.addGpuChains(builder, settings.gpuChains);
  FBReflSettings.addTitle(builder, titleOff);
  const settingsOff = FBReflSettings.endReflSettings(builder);

  let stateOff: flatbuffers.Offset | null = null;
  if (runState !== null) {
    const edVec = FBStochRunState.createEdValuesVector(builder, runState.edValues);
    FBStochRunState.startStochRunState(builder);
    FBStochRunState.addRoughness(builder, runState.roughness);
    FBStochRunState.addFilmAbsInput(builder, runState.filmAbsInput);
    FBStochRunState.addSurfAbs(builder, runState.surfAbs);
    FBStochRunState.addTemperature(builder, runState.temperature);
    FBStochRunState.addImpNorm(builder, runState.impNorm);
    FBStochRunState.addAvgFStun(builder, runState.avgfSTUN);
    FBStochRunState.addBestSolution(builder, runState.bestSolution);
    FBStochRunState.addChiSquare(builder, runState.chiSquare);
    FBStochRunState.addGoodnessOfFit(builder, runState.goodnessOfFit);
    FBStochRunState.addIteration(builder, runState.iteration ?? 0);
    FBStochRunState.addEdValues(builder, edVec);
    stateOff = FBStochRunState.endStochRunState(builder);
  }

  InitRequest.startInitRequest(builder);
  InitRequest.addSettings(builder, settingsOff);
  if (stateOff !== null) InitRequest.addState(builder, stateOff);
  const root = InitRequest.endInitRequest(builder);
  builder.finish(root);

  const buf = builder.asUint8Array();
  fns['Init'](buf, buf.length);

  const errMsg: string = fns['GetInitError']();
  if (errMsg) throw new Error(`StochFit init failed: ${errMsg}`);
}

export function stochStart(iterations: number): void {
  getStochFns()['Start'](iterations);
}

export function stochStop(): void {
  getStochFns()['Stop']();
}

export function stochDestroy(): void {
  getStochFns()['Destroy']();
}

export function stochCancel(): void {
  getStochFns()['Cancel']();
}

// ── Polling ───────────────────────────────────────────────────────────────────

export function stochArraySizes(): { rhoSize: number; reflSize: number } {
  const fns = getStochFns();
  const out = new Uint8Array(MAX_SMALL_BUF);
  const written: number = fns['ArraySizes'](out, out.length);
  const r = readResult(out, written, (bb) => ArraySizesResult.getRootAsArraySizesResult(bb));
  return { rhoSize: r.rhoSize(), reflSize: r.reflSize() };
}

export function stochGetData(): FitData {
  const fns = getStochFns();
  const out = new Uint8Array(MAX_DATA_BUF);
  const written: number = fns['GetData'](out, out.length);
  const r = readResult(out, written, (bb) => GetDataResult.getRootAsGetDataResult(bb));
  return {
    zRange:              Array.from(r.zRangeArray() ?? []),
    rho:                 Array.from(r.rhoArray() ?? []),
    qRange:              Array.from(r.qRangeArray() ?? []),
    refl:                Array.from(r.reflArray() ?? []),
    roughness:           r.roughness(),
    chiSquare:           r.chiSquare(),
    goodnessOfFit:       r.goodnessOfFit(),
    isFinished:          r.isFinished(),
    iterationsCompleted: r.iterationsCompleted(),
  };
}

export function stochGetRunState(boxes: number): StochRunStateOutput {
  const fns = getStochFns();
  const out = new Uint8Array(MAX_STATE_BUF + (boxes + 2) * 8 + 64);
  const written: number = fns['GetRunState'](out, out.length);
  const r = readResult(out, written, (bb) => GetRunStateResult.getRootAsGetRunStateResult(bb));
  const edArr = r.edValuesArray() ?? new Float64Array(0);
  return {
    roughness:      r.roughness(),
    filmAbsInput:   r.filmAbsInput(),
    surfAbs:        r.surfAbs(),
    temperature:    r.temperature(),
    impNorm:        r.impNorm(),
    avgfSTUN:       r.avgFStun(),
    bestSolution:   r.bestSolution(),
    chiSquare:      r.chiSquare(),
    goodnessOfFit:  r.goodnessOfFit(),
    iteration:      0,  // filled by caller from last iterationsCompleted
    edValues:       Array.from(edArr),
    edCount:        edArr.length,
  };
}

export function stochWarmedUp(): boolean {
  return Boolean(getStochFns()['WarmedUp']());
}

export function stochSAParams(): SAParams {
  const fns = getStochFns();
  const out = new Uint8Array(MAX_SMALL_BUF);
  const written: number = fns['SAParams'](out, out.length);
  const r = readResult(out, written, (bb) => SaParamsResult.getRootAsSaParamsResult(bb));
  return { lowestEnergy: r.lowestEnergy(), temp: r.temp(), mode: r.mode() };
}

export function stochGpuAvailable(): boolean {
  return Boolean(getStochFns()['GpuAvailable']());
}

// ── Session file I/O ──────────────────────────────────────────────────────────

export function writeSessionFile(filePath: string, session: StochSessionFile): void {
  const json = JSON.stringify(session, null, 2);
  const tmpPath = filePath + '.tmp';
  fs.writeFileSync(tmpPath, json, 'utf-8');
  try {
    fs.renameSync(tmpPath, filePath);
  } catch {
    try { fs.unlinkSync(tmpPath); } catch { /* ignore */ }
    fs.writeFileSync(filePath, json, 'utf-8');
  }
}

export function readSessionFile(filePath: string): StochSessionFile | null {
  try {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as StochSessionFile;
    if (data.version !== 1) return null;
    if (!data.saState || !Array.isArray(data.saState.edValues)) return null;
    return data;
  } catch {
    return null;
  }
}
